version: '3.3'

services:
    database:
        image: postgres:10.17
        restart: always
        container_name: 'seupc-dev'
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: 'postgresdb-seupc-dev'
        volumes:
            - pg-data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
volumes:
    pg-data:
