version: '3'
services:
  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    volumes:
      - $HOME/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=PgAdmin2024!
      - POSTGRES_DB=postgresdb-seupc-dev
    networks:
      - application
    container_name: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  core-api:
    build:
      context: ./apps/core-api/.
      dockerfile: ./Dockerfile
    image: core-api:v1
    ports:
      - '8080:8080'
    tty: true
    volumes:
      - './apps/core-api:/app'
    networks:
      - application
    container_name: core-api
    depends_on:
      - postgres
    entrypoint: ['/bin/sh', '-c']
    #environment:
    #  - INTEGRATION_TEST_HOST_URL= http://localhost:3002

  client-app:
    build:
      context: ./apps/client-app/.
      dockerfile: ./Dockerfile
    image: client-app
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - ./apps/client-app/:/app
    networks:
      - application
    container_name: client-app
    entrypoint: ['/bin/sh', '-c']
    depends_on:
      - core-api

networks:
  application:
    driver: bridge
